# Generated by Django 5.2.6 on 2025-10-09 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work08", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memo",
            name="content",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="memo",
            name="title",
            field=models.CharField(default="no title", max_length=200),
        ),
    ]
