# Generated by Django 5.2.6 on 2025-10-17 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("artthinking01", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={},
        ),
    ]
