# Generated by Django 5.2.6 on 2026-02-03 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AI_Todo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name="todo",
            old_name="done",
            new_name="is_completed",
        ),
        migrations.RenameField(
            model_name="todo",
            old_name="estimated_minutes",
            new_name="minutes",
        ),
        migrations.RemoveField(
            model_name="todo",
            name="created_at",
        ),
        migrations.AddField(
            model_name="todo",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="AI_Todo.category",
            ),
        ),
    ]
